### ISSUE TITLE
网页正常显示，连不上ZK，改了class里的zk地址

### ISSUE THREAD

**Issue by jiajie999** [triffic-tang/AnotherKafkaMonitor-AKM-#8]
错误信息如下

```org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [SpringMvc] in context with path [/AnotherKafkaMonitor] threw exception [R
equest processing failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0] with root cause
 java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Vector.java:748)
        at cc.triffic.wc.kafkamonitor.utils.ZKPoolUtils.getZkClientSerializer(ZKPoolUtils.java:175)
        at cc.triffic.wc.kafkamonitor.utils.KafkaClusterUtils.getAllPartitions(KafkaClusterUtils.java:353)
        at cc.triffic.wc.kafkamonitor.service.TopicService.list(TopicService.java:18)
        at cc.triffic.wc.kafkamonitor.controller.TopicController.topicListAjax(TopicController.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by triffic-tang** [comment]
贴`system-config.properties`出来看看

**Comment by dede8385** [comment]
我也碰到这样的问题，system-config.properties 配置如下：
-----------------------------------------------------------------
# Zookeeper list
kafka.zk.list=192.169.0.61:2181,192.169.0.62:2181,192.169.0.63:2181

# zk limit
kafka.zk.limit.size=3

# AnotherKafkaMonitor WebUI Port
kafka.eagel.webui.port=8080

# Alarm Email Notice Configuration
anotherkafkamonitor.mail.enable=true
anotherkafkamonitor.mail.username=anotherkafkamonitor@gyj.com
anotherkafkamonitor.mail.password=123456
anotherkafkamonitor.mail.server.host=mail.gyj.com
anotherkafkamonitor.mail.server.port=25

# Alarm Mobile Notice Configuration
anotherkafkamonitor.mobile.enable=false
anotherkafkamonitor.mobile.username=xxx
anotherkafkamonitor.mobile.password=xxx

**Comment by dede8385** [comment]
![image](https://user-images.githubusercontent.com/7520720/34858252-2ed2ac78-f78a-11e7-9d45-38615fd6aa2b.png)
文本的排版有问题，再上传个图片吧！

**Comment by triffic-tang** [comment]
请替换`ZkClient-0.10`试试，[ZkClient-0.10](http://mvnrepository.com/artifact/com.101tec/zkclient/0.10)，若还是不行，请告知。

**Comment by triffic-tang** [comment]
@jiajie999 @dede8385

**Comment by dede8385** [comment]
替换了还是不行。jdk 有要求吗？
是不是我们使用的版本太高了，我的是1.8.0_144的，zk的版本也是3.4.11。
建议用到什么版本？

**Comment by dede8385** [comment]
替换了还是不行。jdk 有要求吗？
是不是我们使用的版本太高了，我的是1.8.0_144的，zk的版本也是3.4.11。
建议用到什么版本？

**Comment by triffic-tang** [comment]
@dede8385 JDK1.8没有本地测过，我有时间本地先测试一下，然后再告知。

**Comment by dede8385** [comment]
OK，建立测试一下目前主流的配置。
JDK: 1.8.0_XXX
ZK: 3.4.1X
TOMCAT:8.X.X

**Comment by dede8385** [comment]
简单的看了下你的源码，我这边的问题是：
ZKPoolUtils.http-nio-8080-exec-2 - INFO  - Initialization ZkClient pool size [0]
ZKPoolUtils 类中的 poolSize 读取配置文件的没有生效，值为0.
